### PR TITLE
Fix stubs for memory send/receive streams

### PR DESCRIPTION
**Pull request by oremanj**
The hooks are optional, and the close hook is a synchronous function.

### CODE REVIEW

**Comment by njsmith** [comment]
I don't know what it means to add the `= ...` syntax, but the rest looks sensible... :-)

**Comment by oremanj** [comment]
`= ...` is how you indicate an unspecified default value in a stubs file. (The type checker doesn't care what the default is, and any specific default might easily get out of sync with the upstream package.)

**Comment by njsmith** [comment]
Ah, so `Optional` means "it could be None", and `= ...` means "it could be left unspecified by the user and a default will be filled in"? That makes sense.

**Comment by oremanj** [comment]
Exactly - thanks for the merge!

**Pull request merged**
